compile_pdf:
  image: aergus/latex
  script:
    - apt-get update -qq && apt-get install -y -qq python3-pip
    - pip3 install -r requirements.txt
    - cd img/standard-map
    - python3 simple-pendulum.py
    - python3 standard-map.py
    - cd ../cw
    - python3 transizione.py
    - cd ../..
    - sed -i 's/\\figureonfalse/\\figureontrue/' main.tex
    - latexmk -pdf main.tex
    - mv main.pdf Sistemi-Dinamici.pdf
  artifacts:
    paths:
      - Sistemi-Dinamici.pdf
